### PR TITLE
Updating location of double-down header files.

### PR DESCRIPTION
**Pull request by pshriwise**
## Description

Addresses a breaking change in double-down by updating the location of header files for that project.

### CODE REVIEW

**Comment by gonuke** [comment]
Do we need to wait for an update to CI images?

**Comment by gonuke** [comment]
I guess not... since the DoubleDown tests are still working...

**Comment by pshriwise** [comment]
Yeah, thankfully we build double-down in CI separately from our Docker images.

**Review by gonuke — APPROVED** [review]
LGTM - thanks @pshriwise.  I'll give @helen-brooks a chance to review as well

**Review by helen-brooks — APPROVED** [review]
All good from my end. I tried out this commit in my docker files that build all the dependencies for AURORA in Fedora 33 and Ubuntu 20.04 and it works just fine.

**Comment by gonuke** [comment]
I think you have merge access, right @helen-brooks - go for it!

**Pull request merged**
