### PR TITLE
One should use direct path whenever possible

### PR DESCRIPTION
**Pull request by bam241**
Changing `DAGMC` relative path to direct path, allowing external inclusion and usage of the different header files

### CODE REVIEW

**Comment by ljacobson64** [comment]
@bam241 Can you add

```
include_directories(${CMAKE_SOURCE_DIR}/src/uwuw)
```

to `src/fluka/CMakeLists.txt`? Apart from this additional needed change this PR LGTM

**Comment by bam241** [comment]
make sense !

**Review by ljacobson64 — COMMENTED** [review]
LGTM!

**Review by ljacobson64 — APPROVED** [review]
LGTM!

**Comment by ljacobson64** [comment]
If there are no more comments, I will merge later today

**Pull request merged**
