### PR TITLE
Adding CMake Version File

### PR DESCRIPTION
**Pull request by pshriwise**
## Description

Addressing #721 here. This is fairly simple -- just adds a version file to simplify any external version checking from other packages.

### CODE REVIEW

**Comment by ljacobson64** [comment]
Just tested this with `find_package(DAGMC REQUIRED VERSION 3.3.0)` and cmake did not give an error

**Comment by pshriwise** [comment]
According to the [`find_package` docs](https://cmake.org/cmake/help/v3.12/command/find_package.html), it would be 

`find_package(DAGMC 3.3.0 REQUIRED)`

to ensure a specific version is found. 

I tried the same as you expecting some kind of warning from CMake about the `VERSION`, but I didn't see anything. Maybe that generally has some other purpose in CMake functions?

**Comment by ljacobson64** [comment]
Ah, so my syntax was wrong. I tested it with the right syntax and it behaves appropriately now.

**Review by ljacobson64 — APPROVED** [review]

**Comment by pshriwise** [comment]
Are we happy with these changes as they are?

**Pull request merged**
