### PR TITLE
Add tests on merge for various upstream packages

### PR DESCRIPTION
**Pull request by gonuke**
## Description
Create a set of separate tests that are run when a PR is merged to identify problems with upstream packages.

## Motivation and Context
We rely on a number of upstream dependencies and currently pin their version to ensure success on our builds.  It is useful, however, to monitor whether or not we break compatibility with an upstream or optional package due to changes in our code base or their code base.

## Changes
Adds three new tests that only occur on merge.  Badges for these tests are at the bottom of the readme for a quick assessment.

Because we are adding the ability to test multiple versions of Geant, this changes to embed the Geant version in the image name.

### CODE REVIEW

**Comment by gonuke** [comment]
Evidence of docker images being built correctly [here](https://github.com/gonuke/DAGMC/actions/runs/5921030727).

**Comment by gonuke** [comment]
When merged, the following should be true:
* MOAB `master` on Ubuntu 22.04 should show success
* Double Down is being build in the docker images with v1.0.0 and will show failure
* Geant4 11.1.1 should show failure (pending updates from #860)

**Comment by gonuke** [comment]
Once merged, we'll need to update the linux build tests for the new image names, in a separate PR.

**Comment by gonuke** [comment]
Any chance that @shimwell or @pshriwise can give this a quick look over before tomorrow's call?

**Comment by shimwell** [comment]
Just reading up on composite actions which are new to me but I have managed to looked over this in time for the call

**Review by pshriwise — APPROVED** [review]
Thanks again for the explanation during the community meeting today @gonuke! I like these composite actions. I'll likely refer to this PR when trying them in the future.

**Pull request merged**
