### PR TITLE
Add fix for broken test

### PR DESCRIPTION
**Pull request by makeclean**
This should fix the issue seen on CI regarding running out of disk space. This issue is correlated with  the Travis image upgrade - https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

### CODE REVIEW

**Comment by makeclean** [comment]
Note, to test correctly, this needs to be merged to develop, then wait for daily testing to run. If it passes no further action is needed, but if it fails, changes should be reverted and another fix attempted.

**Comment by makeclean** [comment]
Merging, hopefully in time for daily CI

**Comment by pshriwise** [comment]
Question: The intent of committing the docker image is to allow one to open a container and debug failing tests, right? Will one have to retrieve those make_watertight regression test files on their own?

**Comment by makeclean** [comment]
The purpose of committing (in this usage) is to allow store the saved state. We dont actually push the image anywhere such that we can retrieve it. We use it such that the CI image can continue running from where it left off.

**Comment by ljacobson64** [comment]
It looks like the CI doesn't fail until it tries to `sudo docker commit` after running the tests. Since running the tests is the last thing it does, perhaps we could remove that last commit?

**Pull request merged**
