### PR TITLE
Moving clang-format installation from script to dockerfile

### PR DESCRIPTION
**Pull request by bam241**
clang-format was previously installed in the housekeeping script.

this make more sense to install it preventively in the docker countainer

### CODE REVIEW

**Comment by bam241** [comment]
this will need the docker container to be update to actually pass... (clang-format will not be in the container...)

**Comment by gonuke** [comment]
Did you manually update the docker images to support testing on this?

**Comment by bam241** [comment]
I did not yet, but we will have to

**Comment by gonuke** [comment]
How are tests passing then?

**Comment by bam241** [comment]
it is actually quietly failing:
```
find: 'clang-format': No such file or directory
find: 'clang-format': No such file or directory
find: 'clang-format': No such file or directory
find: 'clang-format': No such file or directory
````

**Comment by gonuke** [comment]
Do we still need this? update this PR? start over? abandon?

**Comment by bam241** [comment]
we probably still need as our housekeeping script still installs clang-format each time it runs....

**Comment by bam241** [comment]
docker build on my side do net trigger for the last commit...

**Review by gonuke — APPROVED** [review]
This looks good to me.  After #771, the images should build properly on your side.  Or you can add back the blank line before `jobs` in the docker_publish.yml

**Comment by gonuke** [comment]
rebase here and then we can confirm that the images build correctly

**Comment by bam241** [comment]
I did rebased 3 time... the wrong branch :p

**Comment by gonuke** [comment]
I'm monitoring [your test builds](https://github.com/bam241/DAGMC/actions/runs/1060076662) to merge this when it works

**Comment by gonuke** [comment]
Thanks @bam241 - this all build & tested fine

**Pull request merged**
