### PR TITLE
Adding workflow_dispatch option to docker_publish workflow

### PR DESCRIPTION
**Pull request by bam241**
This should also trigger building including clang-format for housekeeping....

I don't know why it was left out....

### CODE REVIEW

**Comment by bam241** [comment]
this is running [here](https://github.com/bam241/DAGMC/actions/runs/1060821864) updated for faeef34

**Comment by bam241** [comment]
this should address #775

**Comment by gonuke** [comment]
Failed housekeeping test on current image and successful housekeeping test on new image are good signs!

**Comment by gonuke** [comment]
Should also address #725

**Comment by bam241** [comment]
> Failed housekeeping test on current image and successful housekeeping test on new image are good signs!

Yes I purposely force the restart of the test for the new image to make sure it was working as I wanted

**Comment by gonuke** [comment]
the images built and tested successfully - thanks @bam241

**Pull request merged**
