### PR TITLE
Add OpenMC to supported list in README

### PR DESCRIPTION
**Pull request by gridley**
self explanatory

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks for this update @gridley - we should have changed it long ago since OpenMC is our primary DAGMC platform these days.  Can you please update the Changelog, either by adding this PR number to an appropriate existing entry, or making a new entry.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Ping @gridley

**Comment by gridley** [comment]
OK, pretty sure it's good to go now!

**Comment by gonuke** [comment]
Thanks @gridley - waiting for tests (but since this only modified docs, they should pass easily)

**Review by ahnaf-tahmid-chowdhury — APPROVED** [review]
All tests are passing now, thanks @gridley.

**Pull request merged**
