### PR TITLE
Add new docker image

### PR DESCRIPTION
**Pull request by ljacobson64**
Submitting this to test the new CI; don't merge

Addresses issue #430

### CODE REVIEW

**Comment by ljacobson64** [comment]
Any idea why this is failing @makeclean ?

```
[ RUN      ] TallyDataDeathTest.ZeroEnergyBins
/root/build/gcc-6/DAGMC-moab-4.9.2/src/tally/tests/test_TallyData.cpp:79: Failure
Death test: TallyData(0, true)
    Result: failed to die.
 Error msg:
[  DEATH   ] 
/root/build/gcc-6/DAGMC-moab-4.9.2/src/tally/tests/test_TallyData.cpp:80: Failure
Death test: TallyData(0, false)
    Result: failed to die.
 Error msg:
[  DEATH   ] 
[  FAILED  ] TallyDataDeathTest.ZeroEnergyBins (8 ms)
[----------] 1 test from TallyDataDeathTest (8 ms total)
```

**Comment by ljacobson64** [comment]
This test passes on my machine; don't have a clue what's going on here

**Comment by makeclean** [comment]
When all none master based test pass, I will merge, you can then make your PR.

**Comment by makeclean** [comment]
Awesome.

**Pull request merged**
