### PR TITLE
Make the MW_REG_TEST_MODELS_URL variable available to the docker image

### PR DESCRIPTION
**Pull request by ljacobson64**
This fixes the problem where all the nightly CI builds were failing. [This Travis build](https://travis-ci.org/svalinn/DAGMC/builds/510079202) shows that this PR fixes the issue.

### CODE REVIEW

**Review by pshriwise — APPROVED** [review]
Looks good @ljacobson64.

**Comment by pshriwise** [comment]
I'll merge on Monday mid-day if there are no other comments.

**Comment by gonuke** [comment]
Thanks @ljacobson64 

For future reference, was there something that you expected to work that didn’t?  Or was it simply a bug in your script from the beginning?

**Comment by ljacobson64** [comment]
As far as I can tell, the make_watertight regression tests were never being run in the past because that environment variable was never being propagated into the docker image, and there was some logic present that said that if that environment variable was empty, don't run the test. My PR caused the make_watertight regression tests to actually attempt to run, and the lack of access to this environment variable inside the docker image led to the tests failing.

**Pull request merged**
