### PR TITLE
Delete unused files

### PR DESCRIPTION
**Pull request by ljacobson64**
All the files in here are either no longer needed or broken. I would be okay with the idea of moving some of these into a `misc` folder instead of deleting them if people would prefer that. Not sure who would volunteer to fix them though.

Here is a list of the files that are deleted:

`gtest/README` and `gtest/configure.sh`: no longer used; last commit in March 2014
`tools/build/*`: no longer used; last commit in June 2014
`cmake/FindPyne.cmake`: no longer used; last commit in June 2014
`tools/finish_dagmc_geom*`: out of date; last commit in June 2014
`tools/txcorp_bld/*`: no idea what this is; last commit in June 2014
`tools/dagmc_tag_eg/*`: out of date; last commit in October 2014
`tally/tools/boundary_correction/*`: broken; last commit in June 2016

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks to version control, deleting files is better than just tucking them away in a directory.

However, it is difficult to ever find them/remember that they were ever there.  One remedy is a really detailed commit message that lists the files (or directories) and what they do.  Another remedy is a ChangeLog that has similar information.

**Comment by gonuke** [comment]
Note that PyNE and Cyclus recently introduced the concept that all PRs must include an RST file in the `news` directory that document the collective changes in that PR.  See pyne/pyne#999 for example.

**Comment by ljacobson64** [comment]
I like the required RST file idea. I could make this PR the first one if we chose to go that route

**Comment by gonuke** [comment]
Let's go ahead with a `news` directory and an RST file with a fixed structure.  The idea for the structure is that it makes it easier to automate change logs during releases.

**Comment by ljacobson64** [comment]
Submitted #545 to handle this

**Comment by ljacobson64** [comment]
Any more comments @gonuke?

**Comment by gonuke** [comment]
Thanks @ljacobson64

**Pull request merged**
