### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by bam241**
This is the PR to issue the Release 3.2.0.

This should not be merged before Monday November 23.
A tag corresponding to the release 3.2.0 will then be issued.

Please pull the `3.2.0-rc2` branch or the `3.2.0-rc2` to test it and verify everything is still working for you.

A full changelog from the previous release can be found on the Release candidate page: https://github.com/svalinn/DAGMC/releases/tag/3.2.0-rc2

If no issue is found this should be merged on November 23.

### CODE REVIEW

**Comment by ljacobson64** [comment]
I pulled the `3.2.0-rc2` branch and I'm getting errors building `fludag`. I'm on Ubuntu 18.04 with gcc/g++/gfortran 7.5.0.

```
[ 50%] Building CXX object src/fluka/CMakeFiles/fludag-shared.dir/fluka_funcs.cpp.o
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp: In function ‘void fludag_write(std::__cxx11::string, std::__cxx11::string)’:
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp:818:52: error: could not convert ‘workflow_data.UWUW::material_library’ from ‘pyne::MaterialLibrary’ to ‘std::map<std::__cxx11::basic_string<char>, pyne::Material>’
   fludagwrite_assignma(assignma_str, workflow_data.material_library);
                                      ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp:836:54: error: could not convert ‘workflow_data.UWUW::material_library’ from ‘pyne::MaterialLibrary’ to ‘std::map<std::__cxx11::basic_string<char>, pyne::Material>’
     fludag_all_materials(material_str, workflow_data.material_library);
                                        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp: In function ‘void fludag_all_tallies(std::ostringstream&, std::map<std::__cxx11::basic_string<char>, pyne::Tally>)’:
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp:987:61: error: ‘class pyne::Tally’ has no member named ‘particle_name’; did you mean ‘particle_names’?
     tally_id = (it->second).tally_type + "/" + (it->second).particle_name;
                                                             ^~~~~~~~~~~~~
                                                             particle_names
/home/lucas/dagmc-build/src/src/fluka/fluka_funcs.cpp:1009:59: error: ‘class pyne::Tally’ has no member named ‘particle_name’; did you mean ‘particle_names’?
     std::string tally_id = tally.tally_type + "/" + tally.particle_name;
                                                           ^~~~~~~~~~~~~
                                                           particle_names
src/fluka/CMakeFiles/fludag-shared.dir/build.make:62: recipe for target 'src/fluka/CMakeFiles/fludag-shared.dir/fluka_funcs.cpp.o' failed
make[2]: *** [src/fluka/CMakeFiles/fludag-shared.dir/fluka_funcs.cpp.o] Error 1
CMakeFiles/Makefile2:2073: recipe for target 'src/fluka/CMakeFiles/fludag-shared.dir/all' failed
make[1]: *** [src/fluka/CMakeFiles/fludag-shared.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ljacobson64** [comment]
Just tested on Ubuntu 20.04 with gcc/g++/gfortran 9.3.0 and got the same error.

**Comment by pshriwise** [comment]
Thanks for checking that @ljacobson64! I created a PR with some fixes. Hopefully, we can resolve it relatively quickly.

**Comment by bam241** [comment]
@ljacobson64 If I am not mistaken, the issues with fluka should have been addressed with #713 PR from @pshriwise .
When you get the time, (after your vacation...) could you confirm this is working :)

Happy Holliday!

**Comment by ljacobson64** [comment]
I just tested this branch and did not encounter any errors. So the problem appears to have been fixed. Merry Christmas!

**Comment by bam241** [comment]
**UPDATE**

This is the PR to issue the Release 3.2.0.
This should not be merged before Monday January 11.
A tag corresponding to the release 3.2.0 will then be issued.

Please pull the 3.2.0-rc2 branch or the 3.2.0-rc2 to test it and verify everything is still working for you.

A full changelog from the previous release can be found on the Release candidate page: https://github.com/svalinn/DAGMC/releases/tag/3.2.0-rc2

Issues were found and fixed this is why the count down has been restarted .
If no issue is found this should be merged on January 11.

**Review by pshriwise — APPROVED** [review]

**Comment by pshriwise** [comment]
We've waited well beyond the window for this and it's time to merge. There are some additional updates and improvements in the pipeline that can be included in an additional mini-release to come soon.

@bam241 and I have coordinated a message to be sent out to the user's list and any other relevant channels. Thanks to all for your contributions to this release!!! :rocket:

**Pull request merged**
