### PR TITLE
Remove eigen3

### LINKED ISSUE #799: Remove need for downstream codes to have Eigen3 installed
**Describe the Bug**<br/>
Currently, any downstream code that links to DAGMC must have Eigen3 installed even if it has no direct dependence on Eigen3.  Eigen3 is a source-code-header only library, so should be compiled into DAGMC libraries and not necessary to build dependent projects.  This problem exists because the DAGMC header is "polluted" with too many other headers.

**To Reproduce**<br/>
Try to build a downstream code, e.g. OpenMC (see discussion in #739), without having Eigen3 installed.

**Expected Behavior**<br/>
Build a downstream code that has no independent/direct dependency on Eigen3 without having Eigen3 installed.

### PR DESCRIPTION
**Pull request by ahnaf-tahmid-chowdhury**
This PR removes Eigen3 from DAGMC dependency.

### CODE REVIEW

**Comment by ahnaf-tahmid-chowdhury** [comment]
What!!! I have turned off BLASLAPACK, but it seems the CMake is still considering it enabled!

**Comment by ahnaf-tahmid-chowdhury** [comment]
I see, we need to enable `blaslapack` and need to find `lapack`, which will enable Fortran support. In that way we can ignore Eigen3 support for MOAB 😕. @gonuke, do you like to proceed with `blaslapack`?

More info: [here](https://bitbucket.org/fathomteam/moab/src/ab73c4a1301bbdaf4cb8bf845389ef8493923317/CMakeLists.txt#lines-264)

**Comment by gonuke** [comment]
We definitely want Eigen3 and not BLAS and LAPACK.

**Comment by gonuke** [comment]
I'm not sure what problem this is trying to solve?

**Comment by ahnaf-tahmid-chowdhury** [comment]
This one #799

**Comment by gonuke** [comment]
> This one #799

I thought that might be it.  This is a different problem.  The problem is not that Eigen3 is a dependency of DAGMC.  The problem is that Eigen3 is included in header files of MOAB and DAGMC that are required by downstream apps, even when it may not be necessary.  The solution to this requires a little more careful analysis of each header file that included Eigen3 headers, moving the Eigen3 include to the source file, and seeing whether some forward declarations are necessary where the Eigen3 has been removed from headers.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Thank you for highlighting the issue with Eigen3 inclusion in header files.

**Pull request closed without merging**
