### PR TITLE
localize git submodule stuff to only when BUILD_UWUW

### LINKED ISSUE #967: Git requires network access for all builds
**Describe the Bug**<br/>
Current build process enforces network access via `git submodule`

**To Reproduce**<br/>
When building DAGMC, CMake either calls `git submodule` or checks to see that the (PyNE) submodule is initialized.  If neither works then it won't build.

**Expected Behavior**<br/>
Since PyNE is the only submodule and we only need it when building with UWUW, these checks should be localized to that condition.

### PR DESCRIPTION
**Pull request by gonuke**
## Description
Fixes #967 

## Changes
Localize the invocation of `git submodules` to occur only when `BUILD_UWUW` is true.

### CODE REVIEW

**Review by pshriwise — COMMENTED** [review]
I was just thinking about this yesterday! Thanks for this @gonuke!

**Review by nuclearkevin — APPROVED** [review]
Thanks @gonuke! I've tested these changes in Cardinal and can confirm that it solves the CIVET issue.

**Review by pshriwise — APPROVED** [review]
These changes look good to me too. 

Not sure what to do about the Windows CI failure. Perhaps using the `auto-update-conda` to update conda in advance in the miniconda action would help?

https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-1-basic-usage

**Comment by gonuke** [comment]
I'm working on the Win failures here: #966

**Comment by gonuke** [comment]
I rebased this on `v3.2.4-rc1` for inclusion in the pending release

**Review by pshriwise — APPROVED** [review]
Looks good to me! Glad the Windows issues were resolved.

**Comment by gonuke** [comment]
> Looks good to me! Glad the Windows issues were resolved.

We decided to "pause" Windows CI, perhaps with plans to deprecate.  It was only ever a priority to support the Cubit plugin, which is no longer a priority.

**Comment by pshriwise** [comment]
> > Looks good to me! Glad the Windows issues were resolved.
> 
> We decided to "pause" Windows CI, perhaps with plans to deprecate. It was only ever a priority to support the Cubit plugin, which is no longer a priority.

Ah, thanks for clarifying! I wasn't following that closely.

**Pull request merged**
