### PR TITLE
A simple html implementation of a slide show for our example images.

### PR DESCRIPTION
**Pull request by Pshriwise**
Adding a slideshow for example images of analysis projects. These are not currently linked to specific pages for each project currently, but they could be in the future.

### CODE REVIEW

**Comment by gonuke** [comment]
Nice!

**Comment by gonuke** [comment]
We could probably autogenerate this from a simple dictionary of `{filename : "title"}` making it easy for people to add new content.  (Not that it's that hard!)  And not that I'm suggesting it as necessary for this PR!

**Comment by makeclean** [comment]
Could you redo the PR against web_update?

**Comment by Pshriwise** [comment]
@makeclean certainly. Closing.

**Pull request closed without merging**
