### PR TITLE
add news checker in the CI-test

### PR DESCRIPTION
**Pull request by bam241**
## Description
Add a news checker to ensure at least one news file is associated with a PR

## Motivation and Context
We are relying on those news files, let's enforce them
## Changes
just add a small script...

### CODE REVIEW

**Comment by bam241** [comment]
@ljacobson64 I am not very comfortable with `travis`, 
could you advice me how to have travis running `news/news_test.sh news` ?

**Comment by pshriwise** [comment]
@bam241 is the current check in `travis.housekeeping.sh` insufficient?

**Comment by bam241** [comment]
I missed that, I was on a mission to add this to all the repos (Cyclus/pyne etc...) 
I'll check it....

**Comment by bam241** [comment]
@pshriwise sorry for the noise... it looks enough :)
already exists... closing....

**Pull request closed without merging**
