### PR TITLE
Script updates

### PR DESCRIPTION
**Pull request by moatazharb**
updated version of uwuw_preproc.py with tests

### CODE REVIEW

**Comment by makeclean** [comment]
Moataz, it looks like your branch is very out of date, you should rebase your branch onto develop and try again.

**Comment by moatazharb** [comment]
Updated uwuw_preproc.py with tests

**Comment by moatazharb** [comment]
I hope this works now!!

**Comment by makeclean** [comment]
@moatazharb could you remove uwuw_preproc and replace it with uwuw_preproc.py, i.e.

     git rm uwuw_preproc
     git mv uwuw_preproc.py uwuw_preproc

I will have a look through your test cases as well, thanks!

**Comment by makeclean** [comment]
@moatazharb is going to update and resubmit this.

**Pull request closed without merging**
