### PR TITLE
Update readme and add SNS image to gallery

### PR DESCRIPTION
**Pull request by ljacobson64**
Our current `README.rst` is pretty out of date. I've replaced it with some text copied from the front page of our website as well as a statement telling people to visit the website if they want more details. I also removed `INSTALL.rst` as it was very out of date.

I also added an SNS proton flux image to the gallery.

### CODE REVIEW

**Comment by ljacobson64** [comment]
This addresses #486

**Comment by pshriwise** [comment]
Do instructions for contributing, testing, and development updates appear somewhere on the website?

**Comment by pshriwise** [comment]
I suppose the information for development updates is somewhat contained on the main DAGMC page, but might still be nice to have a section there for upcoming improvements and work on DAGMC (this could be a separate PR of course). But the instructions for contributing to the website and building documentation in particular might be useful to have somewhere either on the website or in the README

**Comment by pshriwise** [comment]
ping @ljacobson64 

Any thoughts on where notes for contributing/building documentation should go?

**Comment by ljacobson64** [comment]
Notes on building the documentation could go in a readme in the `doc` folder. Not sure about notes on contributing. Perhaps back in the main readme?

**Comment by ljacobson64** [comment]
I added a readme in the `doc` folder. For contributing to the repo, I feel the contributors guide on the website is sufficient.

**Comment by pshriwise** [comment]
Looks good to me @ljacobson64 ! Will merge as soon as checks are complete

**Pull request merged**
