### PR TITLE
Some small fixes to include directories and installed headers.

### PR DESCRIPTION
**Pull request by pshriwise**
A couple small changes to allow the UWUW to be used outside of the DAGMC project after installation.

### CODE REVIEW

**Comment by pshriwise** [comment]
Any thoughts/concerns on this PR?

**Review by gonuke — DISMISSED** [review]
LGTM

**Review by gonuke — APPROVED** [review]
LGTM!

**Comment by gonuke** [comment]
Thanks @pshriwise

**Pull request merged**
