### PR TITLE
Update MOAB to latest

### PR DESCRIPTION
**Pull request by ahnaf-tahmid-chowdhury**
Update MOAB to 5.5.1

### CODE REVIEW

**Review by gonuke — CHANGES_REQUESTED** [review]
We also need to update this in `docker_publish.yml` before we can then also update in `linux_build_test.yml` - ideally in 2 separate PRs

**Comment by ahnaf-tahmid-chowdhury** [comment]
Sorry, I missed to update `docker_publish.yml`. Thanks!

**Comment by ahnaf-tahmid-chowdhury** [comment]
Let's build both 5.4.1 and 5.5.1 images for the history. Later, we may stick with only 5.5.1?

**Review by gonuke — APPROVED** [review]

**Comment by gonuke** [comment]
This LGTM - thanks @ahnaf-tahmid-chowdhury

**Pull request merged**
