### PR TITLE
Add make watertight

### PR DESCRIPTION
**Pull request by Pshriwise**
Brings the make_watertight algorithm and its unit tests into DAGMC. 

Unit tests have been updated to comply with the gtests framework.

### CODE REVIEW

**Comment by makeclean** [comment]
Looks like the tests failed due to the style guide requirement, run

``` tools/astyle_google --style=linux --indent=spaces=2 --exclude=gtest -r *.cpp *.h *.hpp *.cc *.hh```

In the DAGMC  dir

**Comment by Pshriwise** [comment]
Yay green check marks!

**Comment by makeclean** [comment]
This good to go?

**Comment by Pshriwise** [comment]
AFAIK yes.

**Comment by gonuke** [comment]
Do understand correctly that the tests are being run in CI?

**Comment by makeclean** [comment]
It looks like the all tests, except make_watertight tests are run

**Comment by makeclean** [comment]
@Pshriwise add ./make_watertight_cone_tests and ./make_watertight_cylinder_tests to the .travis.yml file, then push again. It looks like you build the tests but CI never runs them.

**Comment by Pshriwise** [comment]
My mistake. Added and pushed. Thanks @makeclean.

**Comment by Pshriwise** [comment]
@makeclean Looks to me like the MOAB Version4.8.2 tests timed out again. Can you confirm?

**Comment by makeclean** [comment]
Im just going to merge, given that all the other MOABs pass. I think we will be ok.

**Pull request merged**
