### PR TITLE
Fix order of attribute initialization

### PR DESCRIPTION
**Pull request by pshriwise**
## Description
This fixes the issue referenced in #902 and is shown in [this CI build failure for that PR](https://github.com/svalinn/DAGMC/actions/runs/6038830737/job/16386056876?pr=902).

## Motivation and Context
Enables builds of DAGMC with MOOSE apps without failure.

## Changes
Small refactor of the metadata class.

### CODE REVIEW

**Comment by pshriwise** [comment]
Any thoughts on this @gonuke, @shimwell?

https://github.com/svalinn/DAGMC/actions/runs/6039003224/job/16386661208

image

**Comment by gonuke** [comment]
This is currently expected to fail.

**Comment by gonuke** [comment]
This test should no longer be run on PRs after my most recent PR (if you rebase?)

**Comment by pshriwise** [comment]
> This is currently expected to fail.

I'd expect #902 to fail due to the additional flags used in CI, but this PR reorders the class attribute initialization so I'd expect it to pass. Am I missing something?

**Comment by gonuke** [comment]
This failing action is to test against new versions of Geant.  I don't see it in your checks for this PR.

**Comment by pshriwise** [comment]
Oh "this" being the CI build, not the PR itself. Though in the end I suppose the outcome is the same... 

All looks well on this PR though 👍🏻 Sorry for the cross-talk.

**Review by gonuke — APPROVED** [review]
Thanks for this quick fix @pshriwise

**Pull request merged**
