### PR TITLE
DO NOT MERGE Rebase dev hzet

### PR DESCRIPTION
**Pull request by dagmcci**

### CODE REVIEW

**Comment by makeclean** [comment]
@julry is this for testing, or would you like this reviewing?

**Comment by julry** [comment]
On 02/11/2015 09:10 AM, Andrew Davis wrote:
>
> @julry <https://github.com/julry> is this for testing, or would you 
> like this reviewing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/svalinn/DAGMC/pull/344#issuecomment-73896498>.
>
No just for testing, I was working on the URL issue (still not solved :()

I noticed the nightly build faild due to CMP0004.  I was just going to 
check that the logic was the correct way round.

Also, I would like to review the big honkin' PR for develop to master, 
if it hasn't already been merged.

Julie

-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Julie C. Zachman
Department of Engineering Physics
jczachman@wisc.edu
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by makeclean** [comment]
The failure is because the PR from develop to master hasnt gone through yet, thats why the nightlies are failing.

**Comment by julry** [comment]
Reviewing now...

**Pull request closed without merging**
