### PR TITLE
Update test to 1.8.0

### PR DESCRIPTION
**Pull request by bam241**
Upgrading test to 1.8.0

### CODE REVIEW

**Comment by bam241** [comment]
@gonuke I did it as a rm commit then an add, GitHub still sees it as a mv....
I'll try again :)

**Comment by pshriwise** [comment]
It's been quite a while since we updated `gtest`, so it's probably good to do so. Curious as to what motivated this PR though!

**Comment by bam241** [comment]
we have problem on the windows side (see #727 ) it needs 1.8.0

**Comment by pshriwise** [comment]
Cool, thanks!

**Comment by gonuke** [comment]
I guess we'll just keep it as a mv...🤷

**Comment by gonuke** [comment]
I'll merge after tests pass

**Comment by gonuke** [comment]
Thanks @bam241

**Pull request merged**
