### PR TITLE
Correcting name of the overlap_check executable directory.

### PR DESCRIPTION
**Pull request by pshriwise**
Fairly self-explanatory.

### CODE REVIEW

**Review by bam241 — APPROVED** [review]
LGTM!
thx @pshriwise

**Comment by bam241** [comment]
merging tonight if no-one does or express a issue with this.

**Comment by bam241** [comment]
@pshriwise I wanted to merge but the travis-ci is still pending...
clicking on `detail` they seem to have passed....

**Comment by pshriwise** [comment]
Just restarted them. We'll see if that fixes it when they complete.

**Review by ljacobson64 — APPROVED** [review]

**Comment by gonuke** [comment]
Thanks @pshriwise

**Pull request merged**
