### PR TITLE
update pyne version to pyne /pyne#85478ba

### PR DESCRIPTION
**Pull request by bam241**
## Description
Update `Pyne` source

## Motivation and Context
Propagate change in Pyne openMC methods

## Changes
update to pyne/pyne #85478ba
I also added a `pyne.version` file in the `PyNE` source folder to inform about the last version of the last update.
A new line will be appended in `pyne.version` with the date and `pyne/pyne` hash used for the update.

### CODE REVIEW

**Comment by gonuke** [comment]
I'd prefer if we could do this with a release of PyNE rather than a hash. 
Maybe we can issue a release?

**Comment by gonuke** [comment]
I just merged an important mod from @ngranda in pyne with the MCNP source functions.  Please rebase for those changes

**Comment by bam241** [comment]
@gonuke done!

**Review by pshriwise — APPROVED** [review]
This looks good to me @bam241. Glad we got the MCNP6 updates in there too.

**Comment by pshriwise** [comment]
Though we don't change the amalgamated PyNE code often, it's a fair amount of overhead to deal with to do a PyNE release each time we want to update it. Would it be satisfactory to require that any release of DagMC have an amalgamated PyNE with an official version?

**Comment by gonuke** [comment]
@pshriwise - so you are suggesting that an official release of DAGMC might trigger an official release of PyNE if the amalgamated PyNE was not yet officially released?

**Comment by pshriwise** [comment]
I'm suggesting that for the `develop` branch of DAGMC, a git hash associated with PyNE is enough. But when it comes time to do a DAGMC release, we would ensure that the amalgamated version of PyNE is for a fixed PyNE release and update the amalgamated PyNE's git hash to that version tag/branch before doing the DAGMC release.

**Comment by pshriwise** [comment]
It looks like the UWUW tests are failing with these changes due to the material name now appearing in XML output for OpenMC. @bam241, I've made a small PR into your branch with the necessary change to get them working.

**Comment by gonuke** [comment]
LGTM - thanks @bam241

**Pull request merged**
