### PR TITLE
Mandated image height in css. Reduces caption text size and moved to …

### PR DESCRIPTION
**Pull request by Pshriwise**
…bottom to avoid interference. Some pics will now require editing if they are landscape.

@ljacobson64 hammer on this a bit and make sure its working ok?

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks @Pshriwise - I'll go ahead and merge this even though it fails CI because CI doesn't really matter for doc changes

**Comment by gonuke** [comment]
I should have looked a little more carefully... this approach distorts images.  We probably need an approach that computes dimensions based on the size of the image using javascript... or to make the images all the right size in at least one dimension?

**Comment by gonuke** [comment]
This will do for now...

**Comment by Pshriwise** [comment]
@gonuke shoot. I'll take a look and see if I can take care of that (in another PR). Can you give me an example of the distortion to look for?

**Pull request merged**
