### PR TITLE
Changelog not news

### PR DESCRIPTION
**Pull request by gonuke**
## Description
Transition from requiring NEWS files to updates of the CHANGELOG

## Motivation and Context
It takes time to combine all the NEWS files at the time of release and this can be distributed among authors of each change.

## Changes
New Github workflow to test for changes in CHANGELOG instead of existing of NEWS file.

### CODE REVIEW

**Comment by gonuke** [comment]
Will consolidate NEWS before making this a real PR

**Comment by bam241** [comment]
we also need another script for syntax.

**Comment by gonuke** [comment]
Need to restore housekeeping because it does style test as well

**Comment by bam241** [comment]
> we also need another script for syntax.

and maybe this could be added in the build and test workflow ?

**Comment by gonuke** [comment]
> > we also need another script for syntax.
> 
> and maybe this could be added in the build and test workflow ?

Maybe as a separate PR

**Comment by gonuke** [comment]
New docker images are being built [here](https://github.com/gonuke/DAGMC/actions/runs/1057725515) (updated)

**Comment by bam241** [comment]
looking good merging after those test passes :)

**Comment by bam241** [comment]
thx @gonuke 
merging

**Pull request merged**
