### PR TITLE
Update pyne

### PR DESCRIPTION
**Pull request by ljacobson64**
This PR edits the `update_pyne` script to also copy over `source.F90` for both MCNP5 and MCNP6. It then runs the script to update amalgamated pyne and both `source.F90`s.

### CODE REVIEW

**Comment by zxkjack123** [comment]
As far as my understanding:
- Two `source.F90` files are alredy reviewed in [pyne PR 1139](https://github.com/pyne/pyne/pull/1139).
- The `pyne.h` and `pyne.cpp` are autogenerated acoording to the current pyne repo
- The `update_pyne.sh` adds the update script for MCNP6 `source.F90`

So, the human made changes are the update of `update_pyne.sh`, adding content about MCNP6 `source.F90`. Is my understading correct?

**Comment by pshriwise** [comment]
That's my understanding too. It looks good tome. I just assigned you because you know these changes best being the one who submitted the PyNE PR.

**Comment by ljacobson64** [comment]
Yes, that is correct. The only file I changed manually was `update_pyne.sh`.

**Comment by zxkjack123** [comment]
Well, it looks good to me.

**Review by zxkjack123 — APPROVED** [review]
Thanks @ljacobson64 . LGTM.

**Pull request merged**
