### PR TITLE
Update to PyNE v0.7.5

### PR DESCRIPTION
**Pull request by gonuke**
This updates the SHA for the PyNE submodule to v0.7.5

### CODE REVIEW

**Comment by gonuke** [comment]
This can wait for #769 so that I don't need to write a news file :)

**Comment by bam241** [comment]
This looks good but need to me rebased.

**Comment by gonuke** [comment]
For some reason, this is building images on my repo?

**Comment by gonuke** [comment]
> For some reason, this is building images on my repo?

(I cancelled it though)

**Comment by bam241** [comment]
> For some reason, this is building images on my repo?

I think there is something we are missing here...

**Comment by bam241** [comment]
I guess it depends on what changed are included in the branch when your are pushing it.

if you develop branch is not up to date... you might include change within the detection path...

**Comment by bam241** [comment]
LTGM!
Merging thx @gonuke

**Pull request merged**
